/*
 * bbdservice.com Inc.
 * Copyright (c) 2017 All Rights Reserved.
 */
package com.bbd.bdsso.common.dal.daointerface;

// auto generated imports
import com.bbd.bdsso.common.dal.dataobject.SsoUserInfoDO;
import org.springframework.dao.DataAccessException;
import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>sso_user_info</tt>.
 *
 * This file is generated by <tt>bdsso-bbdalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bdsso</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/bbdalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/sso_user_info.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bdsso-bbdalgen</tt> 
 * to generate this file.
 *
 * @author Byron Zhang
 * @version $Id: description-java.vm,v 1.1 2016/05/01 07:34:20 byron Exp $
 */
public interface SsoUserInfoDAO {
	/**
	 *  Insert one <tt>SsoUserInfoDO</tt> object to DB table <tt>sso_user_info</tt>, return primary key
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into sso_user_info(user_id,pers_id,name,dept_name,region,law_num,duty,card_id,phone,last_modifier,gmt_create,gmt_modified) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param ssoUserInfo
	 *	@return Integer
	 *	@throws DataAccessException
	 */	 
	Integer insert(SsoUserInfoDO ssoUserInfo) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>sso_user_info</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from sso_user_info where (id = ?)</tt>
	 *
	 *	@param userId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
	int deleteByUserId(Integer userId) throws DataAccessException;

	/**
	 *  Query DB table <tt>sso_user_info</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, user_id, pers_id, name, dept_name, region, law_num, duty, card_id, phone, last_modifier, gmt_create, gmt_modified from sso_user_info</tt>
	 *
	 *	@return List<SsoUserInfoDO>
	 *	@throws DataAccessException
	 */	 
	List<SsoUserInfoDO> queryAll(String region) throws DataAccessException;

	List<SsoUserInfoDO> queryAll() throws DataAccessException;

	/**
	 *  Query DB table <tt>sso_user_info</tt> for records.
	 *
	 *  <p>
	 *  Description for this operation is<br>
	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, user_id, pers_id, name, dept_name, region, law_num, duty, card_id, phone, last_modifier, gmt_create, gmt_modified from sso_user_info</tt>
	 *
	 *	@return List<SsoUserInfoDO>
	 *	@throws DataAccessException
	 */
	List<SsoUserInfoDO> queryByUserIds(List<Integer> userIds) throws DataAccessException;

	/**
	 *  Query DB table <tt>sso_user_info</tt> for records.
	 *
	 *  <p>
	 *  Description for this operation is<br>
	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, user_id, pers_id, name, dept_name, region, law_num, duty, card_id, phone, last_modifier, gmt_create, gmt_modified from sso_user_info</tt>
	 *
	 *	@return List<SsoUserInfoDO>
	 *	@throws DataAccessException
	 */
	SsoUserInfoDO queryByUserId(Integer userId) throws DataAccessException;

	/**
	 *  Query DB table <tt>sso_user_info</tt> for records.
	 *
	 *  <p>
	 *  Description for this operation is<br>
	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, user_id, pers_id, name, dept_name, region, law_num, duty, card_id, phone, last_modifier, gmt_create, gmt_modified from sso_user_info</tt>
	 *
	 *	@return List<SsoUserInfoDO>
	 *	@throws DataAccessException
	 */
	int update(Integer userId,String persId,String name,String deptName,String region,String lawNum,String duty,String cardId,String phone,String lastModifier) throws DataAccessException;
}