/*
 * bbdservice.com Inc.
 * Copyright (c) 2017 All Rights Reserved.
 */
package com.bbd.bdsso.common.dal.dataobject;

import java.io.Serializable;
// auto generated imports

import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

/**
 * A data object class directly models database table <tt>sso_data_dictionary</tt>.
 *
 * This file is generated by <tt>bdsso-bbdalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bdsso</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/bbdalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/sso_data_dictionary.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bdsso-bbdalgen</tt> 
 * to generate this file.
 *
 * @author Byron Zhang
 * @version $Id: description-java.vm,v 1.1 2016/05/01 07:34:20 byron Exp $
 */
public class SsoDataDictionaryDO implements Serializable {

	/** serialId */
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.
	 */
	private Integer id;

	/**
	 * This property corresponds to db column <tt>data_type</tt>.
	 */
	private String dataType;

	/**
	 * This property corresponds to db column <tt>data_code</tt>.
	 */
	private String dataCode;

	/**
	 * This property corresponds to db column <tt>data_name</tt>.
	 */
	private String dataName;

	/**
	 * This property corresponds to db column <tt>seq_num</tt>.
	 */
	private int seqNum;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public Integer getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(Integer id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>dataType</tt>.
     *
     * @return property value of dataType
     */
	public String getDataType() {
		return dataType;
	}
	
	/**
	 * Setter method for property <tt>dataType</tt>.
	 * 
	 * @param dataType value to be assigned to property dataType
     */
	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

    /**
     * Getter method for property <tt>dataCode</tt>.
     *
     * @return property value of dataCode
     */
	public String getDataCode() {
		return dataCode;
	}
	
	/**
	 * Setter method for property <tt>dataCode</tt>.
	 * 
	 * @param dataCode value to be assigned to property dataCode
     */
	public void setDataCode(String dataCode) {
		this.dataCode = dataCode;
	}

    /**
     * Getter method for property <tt>dataName</tt>.
     *
     * @return property value of dataName
     */
	public String getDataName() {
		return dataName;
	}
	
	/**
	 * Setter method for property <tt>dataName</tt>.
	 * 
	 * @param dataName value to be assigned to property dataName
     */
	public void setDataName(String dataName) {
		this.dataName = dataName;
	}

    /**
     * Getter method for property <tt>seqNum</tt>.
     *
     * @return property value of seqNum
     */
	public int getSeqNum() {
		return seqNum;
	}
	
	/**
	 * Setter method for property <tt>seqNum</tt>.
	 * 
	 * @param seqNum value to be assigned to property seqNum
     */
	public void setSeqNum(int seqNum) {
		this.seqNum = seqNum;
	}

    /** 
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
