/*
 * bbdservice.com Inc.
 * Copyright (c) 2017 All Rights Reserved.
 */
package com.bbd.bdsso.common.dal.dataobject;

import java.io.Serializable;
// auto generated imports
import java.util.Date;

import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

/**
 * A data object class directly models database table <tt>sso_user_info</tt>.
 *
 * This file is generated by <tt>bdsso-bbdalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bdsso</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/bbdalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/sso_user_info.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bdsso-bbdalgen</tt> 
 * to generate this file.
 *
 * @author Byron Zhang
 * @version $Id: description-java.vm,v 1.1 2016/05/01 07:34:20 byron Exp $
 */
public class SsoUserInfoDO implements Serializable {

	/** serialId */
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.
	 */
	private Integer id;

	/**
	 * This property corresponds to db column <tt>user_id</tt>.
	 */
	private int userId;

	/**
	 * This property corresponds to db column <tt>pers_id</tt>.
	 */
	private String persId;

	/**
	 * This property corresponds to db column <tt>name</tt>.
	 */
	private String name;

	/**
	 * This property corresponds to db column <tt>dept_name</tt>.
	 */
	private String deptName;

	/**
	 * This property corresponds to db column <tt>region</tt>.
	 */
	private String region;

	/**
	 * This property corresponds to db column <tt>law_num</tt>.
	 */
	private String lawNum;

	/**
	 * This property corresponds to db column <tt>duty</tt>.
	 */
	private String duty;

	/**
	 * This property corresponds to db column <tt>card_id</tt>.
	 */
	private String cardId;

	/**
	 * This property corresponds to db column <tt>phone</tt>.
	 */
	private String phone;

	/**
	 * This property corresponds to db column <tt>last_modifier</tt>.
	 */
	private String lastModifier;

	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.
	 */
	private Date gmtModified;

	private String userName;

	//========== getters and setters ==========

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public Integer getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(Integer id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>userId</tt>.
     *
     * @return property value of userId
     */
	public int getUserId() {
		return userId;
	}
	
	/**
	 * Setter method for property <tt>userId</tt>.
	 * 
	 * @param userId value to be assigned to property userId
     */
	public void setUserId(int userId) {
		this.userId = userId;
	}

    /**
     * Getter method for property <tt>persId</tt>.
     *
     * @return property value of persId
     */
	public String getPersId() {
		return persId;
	}
	
	/**
	 * Setter method for property <tt>persId</tt>.
	 * 
	 * @param persId value to be assigned to property persId
     */
	public void setPersId(String persId) {
		this.persId = persId;
	}

    /**
     * Getter method for property <tt>name</tt>.
     *
     * @return property value of name
     */
	public String getName() {
		return name;
	}
	
	/**
	 * Setter method for property <tt>name</tt>.
	 * 
	 * @param name value to be assigned to property name
     */
	public void setName(String name) {
		this.name = name;
	}

    /**
     * Getter method for property <tt>deptName</tt>.
     *
     * @return property value of deptName
     */
	public String getDeptName() {
		return deptName;
	}
	
	/**
	 * Setter method for property <tt>deptName</tt>.
	 * 
	 * @param deptName value to be assigned to property deptName
     */
	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

    /**
     * Getter method for property <tt>region</tt>.
     *
     * @return property value of region
     */
	public String getRegion() {
		return region;
	}
	
	/**
	 * Setter method for property <tt>region</tt>.
	 * 
	 * @param region value to be assigned to property region
     */
	public void setRegion(String region) {
		this.region = region;
	}

    /**
     * Getter method for property <tt>lawNum</tt>.
     *
     * @return property value of lawNum
     */
	public String getLawNum() {
		return lawNum;
	}
	
	/**
	 * Setter method for property <tt>lawNum</tt>.
	 * 
	 * @param lawNum value to be assigned to property lawNum
     */
	public void setLawNum(String lawNum) {
		this.lawNum = lawNum;
	}

    /**
     * Getter method for property <tt>duty</tt>.
     *
     * @return property value of duty
     */
	public String getDuty() {
		return duty;
	}
	
	/**
	 * Setter method for property <tt>duty</tt>.
	 * 
	 * @param duty value to be assigned to property duty
     */
	public void setDuty(String duty) {
		this.duty = duty;
	}

    /**
     * Getter method for property <tt>cardId</tt>.
     *
     * @return property value of cardId
     */
	public String getCardId() {
		return cardId;
	}
	
	/**
	 * Setter method for property <tt>cardId</tt>.
	 * 
	 * @param cardId value to be assigned to property cardId
     */
	public void setCardId(String cardId) {
		this.cardId = cardId;
	}

    /**
     * Getter method for property <tt>phone</tt>.
     *
     * @return property value of phone
     */
	public String getPhone() {
		return phone;
	}
	
	/**
	 * Setter method for property <tt>phone</tt>.
	 * 
	 * @param phone value to be assigned to property phone
     */
	public void setPhone(String phone) {
		this.phone = phone;
	}

    /**
     * Getter method for property <tt>lastModifier</tt>.
     *
     * @return property value of lastModifier
     */
	public String getLastModifier() {
		return lastModifier;
	}
	
	/**
	 * Setter method for property <tt>lastModifier</tt>.
	 * 
	 * @param lastModifier value to be assigned to property lastModifier
     */
	public void setLastModifier(String lastModifier) {
		this.lastModifier = lastModifier;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

    /** 
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
