/*
 * bbdservice.com Inc.
 * Copyright (c) 2017 All Rights Reserved.
 */
package com.bbd.bdsso.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.bbd.bdsso.common.dal.daointerface.SsoDataDictionaryDAO;

// auto generated imports
import com.bbd.bdsso.common.dal.dataobject.SsoDataDictionaryDO;
import org.springframework.dao.DataAccessException;

import java.util.List;

/**
 * An ibatis based implementation of dao interface <tt>com.bbd.bdsso.common.dal.daointerface.SsoDataDictionaryDAO</tt>.
 *
 * This file is generated by <tt>bdsso-bbdalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bdsso</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/bbdalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/sso_data_dictionary.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bdsso-bbdalgen</tt> 
 * to generate this file.
 *
 * @author Byron Zhang
 * @version $Id: description-java.vm,v 1.1 2016/05/01 07:34:20 byron Exp $
 */
public class IbatisSsoDataDictionaryDAO extends SqlMapClientDaoSupport implements SsoDataDictionaryDAO {
	/**
	 *  Query DB table <tt>sso_data_dictionary</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, data_code, data_name from sso_data_dictionary where (data_type = ?) order by seq_num ASC</tt>
	 *
	 *	@param dataType
	 *	@return SsoDataDictionaryDO
	 *	@throws DataAccessException
	 */	 
    public List<SsoDataDictionaryDO> queryByType(String dataType) throws DataAccessException {

        return (List<SsoDataDictionaryDO>) getSqlMapClientTemplate().queryForList("MS-SSO-DATA-DICTIONARY-QUERY-BY-TYPE", dataType);

    }

}